/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CardioSession {
  'cardioType' : CardioType,
  'distanceKm' : [] | [number],
  'durationMinutes' : bigint,
  'caloriesBurned' : [] | [bigint],
}
export type CardioType = { 'swimming' : null } |
  { 'other' : null } |
  { 'walking' : null } |
  { 'cycling' : null } |
  { 'running' : null };
export interface DailyGoals {
  'workoutDaysPerWeek' : bigint,
  'stepGoal' : bigint,
  'cardioMinutesPerWeek' : bigint,
  'waterGoal' : bigint,
}
export interface Exercise {
  'weight' : [] | [number],
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'category' : ExerciseCategory,
}
export type ExerciseCategory = { 'arms' : null } |
  { 'back' : null } |
  { 'core' : null } |
  { 'chest' : null } |
  { 'legs' : null } |
  { 'cardio' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutEntry { 'date' : Time, 'exercises' : Array<Exercise> }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCardioHistory' : ActorMethod<[], Array<CardioSession>>,
  'getDailyGoals' : ActorMethod<[], [] | [DailyGoals]>,
  'getExerciseLibrary' : ActorMethod<[], Array<Exercise>>,
  'getStepHistory' : ActorMethod<[], Array<bigint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWaterIntakeHistory' : ActorMethod<[], Array<bigint>>,
  'getWorkoutHistory' : ActorMethod<[], Array<WorkoutEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logCardio' : ActorMethod<[CardioSession], undefined>,
  'logSteps' : ActorMethod<[bigint], undefined>,
  'logWaterGlasses' : ActorMethod<[bigint], undefined>,
  'logWorkout' : ActorMethod<[WorkoutEntry], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDailyGoals' : ActorMethod<[DailyGoals], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];