/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CardioType = IDL.Variant({
  'swimming' : IDL.Null,
  'other' : IDL.Null,
  'walking' : IDL.Null,
  'cycling' : IDL.Null,
  'running' : IDL.Null,
});
export const CardioSession = IDL.Record({
  'cardioType' : CardioType,
  'distanceKm' : IDL.Opt(IDL.Float64),
  'durationMinutes' : IDL.Nat,
  'caloriesBurned' : IDL.Opt(IDL.Nat),
});
export const DailyGoals = IDL.Record({
  'workoutDaysPerWeek' : IDL.Nat,
  'stepGoal' : IDL.Nat,
  'cardioMinutesPerWeek' : IDL.Nat,
  'waterGoal' : IDL.Nat,
});
export const ExerciseCategory = IDL.Variant({
  'arms' : IDL.Null,
  'back' : IDL.Null,
  'core' : IDL.Null,
  'chest' : IDL.Null,
  'legs' : IDL.Null,
  'cardio' : IDL.Null,
});
export const Exercise = IDL.Record({
  'weight' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'category' : ExerciseCategory,
});
export const Time = IDL.Int;
export const WorkoutEntry = IDL.Record({
  'date' : Time,
  'exercises' : IDL.Vec(Exercise),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCardioHistory' : IDL.Func([], [IDL.Vec(CardioSession)], ['query']),
  'getDailyGoals' : IDL.Func([], [IDL.Opt(DailyGoals)], ['query']),
  'getExerciseLibrary' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getStepHistory' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaterIntakeHistory' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logCardio' : IDL.Func([CardioSession], [], []),
  'logSteps' : IDL.Func([IDL.Nat], [], []),
  'logWaterGlasses' : IDL.Func([IDL.Nat], [], []),
  'logWorkout' : IDL.Func([WorkoutEntry], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDailyGoals' : IDL.Func([DailyGoals], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CardioType = IDL.Variant({
    'swimming' : IDL.Null,
    'other' : IDL.Null,
    'walking' : IDL.Null,
    'cycling' : IDL.Null,
    'running' : IDL.Null,
  });
  const CardioSession = IDL.Record({
    'cardioType' : CardioType,
    'distanceKm' : IDL.Opt(IDL.Float64),
    'durationMinutes' : IDL.Nat,
    'caloriesBurned' : IDL.Opt(IDL.Nat),
  });
  const DailyGoals = IDL.Record({
    'workoutDaysPerWeek' : IDL.Nat,
    'stepGoal' : IDL.Nat,
    'cardioMinutesPerWeek' : IDL.Nat,
    'waterGoal' : IDL.Nat,
  });
  const ExerciseCategory = IDL.Variant({
    'arms' : IDL.Null,
    'back' : IDL.Null,
    'core' : IDL.Null,
    'chest' : IDL.Null,
    'legs' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'weight' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'category' : ExerciseCategory,
  });
  const Time = IDL.Int;
  const WorkoutEntry = IDL.Record({
    'date' : Time,
    'exercises' : IDL.Vec(Exercise),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCardioHistory' : IDL.Func([], [IDL.Vec(CardioSession)], ['query']),
    'getDailyGoals' : IDL.Func([], [IDL.Opt(DailyGoals)], ['query']),
    'getExerciseLibrary' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getStepHistory' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaterIntakeHistory' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logCardio' : IDL.Func([CardioSession], [], []),
    'logSteps' : IDL.Func([IDL.Nat], [], []),
    'logWaterGlasses' : IDL.Func([IDL.Nat], [], []),
    'logWorkout' : IDL.Func([WorkoutEntry], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDailyGoals' : IDL.Func([DailyGoals], [], []),
  });
};

export const init = ({ IDL }) => { return []; };