/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    weight?: number;
    name: string;
    reps: bigint;
    sets: bigint;
    category: ExerciseCategory;
}
export interface CardioSession {
    cardioType: CardioType;
    distanceKm?: number;
    durationMinutes: bigint;
    caloriesBurned?: bigint;
}
export type Time = bigint;
export interface DailyGoals {
    workoutDaysPerWeek: bigint;
    stepGoal: bigint;
    cardioMinutesPerWeek: bigint;
    waterGoal: bigint;
}
export interface WorkoutEntry {
    date: Time;
    exercises: Array<Exercise>;
}
export interface UserProfile {
    name: string;
}
export enum CardioType {
    swimming = "swimming",
    other = "other",
    walking = "walking",
    cycling = "cycling",
    running = "running"
}
export enum ExerciseCategory {
    arms = "arms",
    back = "back",
    core = "core",
    chest = "chest",
    legs = "legs",
    cardio = "cardio"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCardioHistory(): Promise<Array<CardioSession>>;
    getDailyGoals(): Promise<DailyGoals | null>;
    getExerciseLibrary(): Promise<Array<Exercise>>;
    getStepHistory(): Promise<Array<bigint>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWaterIntakeHistory(): Promise<Array<bigint>>;
    getWorkoutHistory(): Promise<Array<WorkoutEntry>>;
    isCallerAdmin(): Promise<boolean>;
    logCardio(cardio: CardioSession): Promise<void>;
    logSteps(steps: bigint): Promise<void>;
    logWaterGlasses(glasses: bigint): Promise<void>;
    logWorkout(workout: WorkoutEntry): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setDailyGoals(goals: DailyGoals): Promise<void>;
}
import type { CardioSession as _CardioSession, CardioType as _CardioType, DailyGoals as _DailyGoals, Exercise as _Exercise, ExerciseCategory as _ExerciseCategory, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WorkoutEntry as _WorkoutEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCardioHistory(): Promise<Array<CardioSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardioHistory();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardioHistory();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyGoals(): Promise<DailyGoals | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyGoals();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyGoals();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExerciseLibrary(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExerciseLibrary();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExerciseLibrary();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStepHistory(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStepHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStepHistory();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaterIntakeHistory(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaterIntakeHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaterIntakeHistory();
            return result;
        }
    }
    async getWorkoutHistory(): Promise<Array<WorkoutEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutHistory();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutHistory();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logCardio(arg0: CardioSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logCardio(to_candid_CardioSession_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logCardio(to_candid_CardioSession_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async logSteps(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logSteps(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSteps(arg0);
            return result;
        }
    }
    async logWaterGlasses(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWaterGlasses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWaterGlasses(arg0);
            return result;
        }
    }
    async logWorkout(arg0: WorkoutEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkout(to_candid_WorkoutEntry_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkout(to_candid_WorkoutEntry_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setDailyGoals(arg0: DailyGoals): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDailyGoals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDailyGoals(arg0);
            return result;
        }
    }
}
function from_candid_CardioSession_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardioSession): CardioSession {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_CardioType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardioType): CardioType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ExerciseCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseCategory): ExerciseCategory {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutEntry_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutEntry): WorkoutEntry {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyGoals]): DailyGoals | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: [] | [number];
    name: string;
    reps: bigint;
    sets: bigint;
    category: _ExerciseCategory;
}): {
    weight?: number;
    name: string;
    reps: bigint;
    sets: bigint;
    category: ExerciseCategory;
} {
    return {
        weight: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.weight)),
        name: value.name,
        reps: value.reps,
        sets: value.sets,
        category: from_candid_ExerciseCategory_n17(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    exercises: Array<_Exercise>;
}): {
    date: Time;
    exercises: Array<Exercise>;
} {
    return {
        date: value.date,
        exercises: from_candid_vec_n14(_uploadFile, _downloadFile, value.exercises)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cardioType: _CardioType;
    distanceKm: [] | [number];
    durationMinutes: bigint;
    caloriesBurned: [] | [bigint];
}): {
    cardioType: CardioType;
    distanceKm?: number;
    durationMinutes: bigint;
    caloriesBurned?: bigint;
} {
    return {
        cardioType: from_candid_CardioType_n9(_uploadFile, _downloadFile, value.cardioType),
        distanceKm: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.distanceKm)),
        durationMinutes: value.durationMinutes,
        caloriesBurned: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.caloriesBurned))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    swimming: null;
} | {
    other: null;
} | {
    walking: null;
} | {
    cycling: null;
} | {
    running: null;
}): CardioType {
    return "swimming" in value ? CardioType.swimming : "other" in value ? CardioType.other : "walking" in value ? CardioType.walking : "cycling" in value ? CardioType.cycling : "running" in value ? CardioType.running : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
} | {
    cardio: null;
}): ExerciseCategory {
    return "arms" in value ? ExerciseCategory.arms : "back" in value ? ExerciseCategory.back : "core" in value ? ExerciseCategory.core : "chest" in value ? ExerciseCategory.chest : "legs" in value ? ExerciseCategory.legs : "cardio" in value ? ExerciseCategory.cardio : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutEntry>): Array<WorkoutEntry> {
    return value.map((x)=>from_candid_WorkoutEntry_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CardioSession>): Array<CardioSession> {
    return value.map((x)=>from_candid_CardioSession_n7(_uploadFile, _downloadFile, x));
}
function to_candid_CardioSession_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardioSession): _CardioSession {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_CardioType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardioType): _CardioType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_ExerciseCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExerciseCategory): _ExerciseCategory {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Exercise_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Exercise): _Exercise {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutEntry_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutEntry): _WorkoutEntry {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cardioType: CardioType;
    distanceKm?: number;
    durationMinutes: bigint;
    caloriesBurned?: bigint;
}): {
    cardioType: _CardioType;
    distanceKm: [] | [number];
    durationMinutes: bigint;
    caloriesBurned: [] | [bigint];
} {
    return {
        cardioType: to_candid_CardioType_n24(_uploadFile, _downloadFile, value.cardioType),
        distanceKm: value.distanceKm ? candid_some(value.distanceKm) : candid_none(),
        durationMinutes: value.durationMinutes,
        caloriesBurned: value.caloriesBurned ? candid_some(value.caloriesBurned) : candid_none()
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Time;
    exercises: Array<Exercise>;
}): {
    date: _Time;
    exercises: Array<_Exercise>;
} {
    return {
        date: value.date,
        exercises: to_candid_vec_n28(_uploadFile, _downloadFile, value.exercises)
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight?: number;
    name: string;
    reps: bigint;
    sets: bigint;
    category: ExerciseCategory;
}): {
    weight: [] | [number];
    name: string;
    reps: bigint;
    sets: bigint;
    category: _ExerciseCategory;
} {
    return {
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        name: value.name,
        reps: value.reps,
        sets: value.sets,
        category: to_candid_ExerciseCategory_n31(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardioType): {
    swimming: null;
} | {
    other: null;
} | {
    walking: null;
} | {
    cycling: null;
} | {
    running: null;
} {
    return value == CardioType.swimming ? {
        swimming: null
    } : value == CardioType.other ? {
        other: null
    } : value == CardioType.walking ? {
        walking: null
    } : value == CardioType.cycling ? {
        cycling: null
    } : value == CardioType.running ? {
        running: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExerciseCategory): {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
} | {
    cardio: null;
} {
    return value == ExerciseCategory.arms ? {
        arms: null
    } : value == ExerciseCategory.back ? {
        back: null
    } : value == ExerciseCategory.core ? {
        core: null
    } : value == ExerciseCategory.chest ? {
        chest: null
    } : value == ExerciseCategory.legs ? {
        legs: null
    } : value == ExerciseCategory.cardio ? {
        cardio: null
    } : value;
}
function to_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Exercise>): Array<_Exercise> {
    return value.map((x)=>to_candid_Exercise_n29(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
